from django.urls import path

from . import views

app_name = "pwms"

urlpatterns = [
    path("", views.index, name="home"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("workflows/", views.workflows, name="workflows"),
    # One instrument as a formal, filed-style document (PDF or HTML). Keyed by
    # public id rather than by type, so every instrument shares one route.
    path(
        "instruments/<uuid:public_id>/document/",
        views.workflow_document,
        name="workflow_document",
    ),
    # The state-machine diagram for the instance's workflow type, served for the
    # detail page's Diagram tab (generated by `manage.py generate_diagrams`).
    path(
        "instruments/<uuid:public_id>/diagram.svg",
        views.workflow_diagram,
        name="workflow_diagram",
    ),
    # Delegation reports
    path(
        "workflows/delegation-reports/",
        views.delegation_reports,
        name="delegation_reports",
    ),
    path(
        "workflows/delegation-reports/new/",
        views.delegation_report_create,
        name="delegation_report_create",
    ),
    path(
        "workflows/delegation-reports/<uuid:public_id>/",
        views.delegation_report_detail,
        name="delegation_report_detail",
    ),
    path(
        "workflows/delegation-reports/<uuid:public_id>/edit/",
        views.delegation_report_update,
        name="delegation_report_update",
    ),
    path(
        "workflows/delegation-reports/<uuid:public_id>/delete/",
        views.delegation_report_delete,
        name="delegation_report_delete",
    ),
    # International resolutions
    path(
        "workflows/international-resolutions/",
        views.international_resolutions,
        name="international_resolutions",
    ),
    path(
        "workflows/international-resolutions/new/",
        views.international_resolution_create,
        name="international_resolution_create",
    ),
    path(
        "workflows/international-resolutions/<uuid:public_id>/",
        views.international_resolution_detail,
        name="international_resolution_detail",
    ),
    path(
        "workflows/international-resolutions/<uuid:public_id>/edit/",
        views.international_resolution_update,
        name="international_resolution_update",
    ),
    path(
        "workflows/international-resolutions/<uuid:public_id>/delete/",
        views.international_resolution_delete,
        name="international_resolution_delete",
    ),
    # International agreements
    path(
        "workflows/international-agreements/",
        views.international_agreements,
        name="international_agreements",
    ),
    path(
        "workflows/international-agreements/new/",
        views.international_agreement_create,
        name="international_agreement_create",
    ),
    path(
        "workflows/international-agreements/<uuid:public_id>/",
        views.international_agreement_detail,
        name="international_agreement_detail",
    ),
    path(
        "workflows/international-agreements/<uuid:public_id>/edit/",
        views.international_agreement_update,
        name="international_agreement_update",
    ),
    path(
        "workflows/international-agreements/<uuid:public_id>/delete/",
        views.international_agreement_delete,
        name="international_agreement_delete",
    ),
    # Bills
    path("workflows/bills/", views.bills, name="bills"),
    path("workflows/bills/new/", views.bill_create, name="bill_create"),
    path(
        "workflows/bills/<uuid:public_id>/",
        views.bill_detail,
        name="bill_detail",
    ),
    path(
        "workflows/bills/<uuid:public_id>/edit/",
        views.bill_update,
        name="bill_update",
    ),
    path(
        "workflows/bills/<uuid:public_id>/versions/new/",
        views.bill_version_create,
        name="bill_version_create",
    ),
    path(
        "workflows/bills/<uuid:public_id>/versions/<uuid:version_public_id>/edit/",
        views.bill_version_update,
        name="bill_version_update",
    ),
    path(
        "workflows/bills/<uuid:public_id>/delete/",
        views.bill_delete,
        name="bill_delete",
    ),
    # User search
    path("user-search/", views.user_search, name="user_search"),
    # Group search for dynamic lookup
    path("group-search/", views.group_search, name="group_search"),
    # Delegation report lookup (the resolution form's parent picker)
    path("report-search/", views.report_search, name="report_search"),
    # Country / city lookup for the engagement location pickers
    path("country-search/", views.country_search, name="country_search"),
    path("city-search/", views.city_search, name="city_search"),
    # Attachments: the SharePoint document picker plus its link/upload/delete
    # actions. Each route names its target record, so the same views serve every
    # concrete workflow subclass (see pwms.views._attachment_target).
    path(
        "attachments/browser/",
        views.attachment_browser,
        name="attachment_browser",
    ),
    path(
        "attachments/tree/",
        views.attachment_tree_children,
        name="attachment_tree_children",
    ),
    path(
        "attachments/folder/",
        views.attachment_folder,
        name="attachment_folder",
    ),
    path("attachments/link/", views.attachment_link, name="attachment_link"),
    path("attachments/upload/", views.attachment_upload, name="attachment_upload"),
    path(
        "attachments/<uuid:public_id>/delete/",
        views.attachment_delete,
        name="attachment_delete",
    ),
    path(
        "attachments/<uuid:public_id>/versions/",
        views.attachment_versions,
        name="attachment_versions",
    ),
    path(
        "attachments/versions/<uuid:public_id>/download/",
        views.attachment_version_download,
        name="attachment_version_download",
    ),
    path("groups/mine/", views.my_groups, name="my_groups"),
    path("groups/all/", views.all_groups, name="all_groups"),
    path("groups/<int:pk>/", views.group_detail, name="group_detail"),
    # Alerts: the bell menu, its page, and the read state of both. "read-all" is
    # declared before the <uuid> route so the literal always wins the match.
    path("alerts/", views.notifications, name="notifications"),
    path(
        "alerts/read-all/",
        views.notifications_read_all,
        name="notifications_read_all",
    ),
    path(
        "alerts/<uuid:public_id>/",
        views.notification_open,
        name="notification_open",
    ),
    # Reports: the builder page, the HTMX preview it swaps in, the export
    # stream and the share flow (mint a link, then the read-only shared view).
    path("reports/", views.reports, name="reports"),
    path("reports/preview/", views.reports_preview, name="reports_preview"),
    path("reports/export/", views.reports_export, name="reports_export"),
    path("reports/share/", views.reports_share, name="reports_share"),
    path(
        "reports/shared/<str:token>/",
        views.report_shared,
        name="report_shared",
    ),
    path("about/", views.about, name="about"),
    path("contact/", views.contact, name="contact"),
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
]
