# Generated by Django 6.1.1 on 2026-09-09 22:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pwms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SharepointToken",
            fields=[
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid7,
                        editable=False,
                        help_text="Public UUIDv7 identifier for external references and API routes.",
                        unique=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("access_token", models.TextField(help_text="Sharepoint access token")),
                (
                    "refresh_token",
                    models.TextField(blank=True, help_text="Sharepoint refresh token"),
                ),
                ("expires_at", models.DateTimeField(help_text="Token expiration time")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this token is active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterField(
            model_name="group",
            name="group_type",
            field=models.CharField(
                choices=[
                    ("legislature", "Legislature"),
                    ("parliament", "Parliament"),
                    ("house", "House"),
                    ("committee", "Committee"),
                    ("member", "Member"),
                    ("portfolio_committee", "Portfolio Committee"),
                    ("select_committee", "Select Committee"),
                    ("special_committee", "Special Committee"),
                    ("public_accounts_committee", "Public Accounts Committee"),
                    ("internal_committee", "Internal Committee"),
                    ("ad_hoc_committee", "Ad Hoc Committee"),
                    ("joint_committee", "Joint Committee"),
                    ("administration", "Administration"),
                    ("office", "Office"),
                    ("division", "Division"),
                    ("section", "Section"),
                    ("business_unit", "Business Unit"),
                    ("party", "Party"),
                    ("executive", "Executive"),
                    ("presidency", "Presidency"),
                    ("ministry", "Ministry"),
                    ("municipality", "Municipality"),
                    ("department", "Department"),
                    ("province", "Province"),
                    ("premier", "Premier"),
                    ("delegation", "Delegation"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="SharepointSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid7,
                        editable=False,
                        help_text="Public UUIDv7 identifier for external references and API routes.",
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("url", models.URLField()),
                ("site_id", models.CharField(max_length=200)),
                ("is_personal_site", models.BooleanField(default=False)),
                (
                    "last_synced_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When this record was last refreshed from Sharepoint.",
                    ),
                ),
                (
                    "remote_modified_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="The last modified timestamp reported by Sharepoint for this site.",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SharepointDrive",
            fields=[
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid7,
                        editable=False,
                        help_text="Public UUIDv7 identifier for external references and API routes.",
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("drive_id", models.CharField(max_length=200)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pwms.sharepointsite",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SharepointFolder",
            fields=[
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid7,
                        editable=False,
                        help_text="Public UUIDv7 identifier for external references and API routes.",
                        unique=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "folder_id",
                    models.CharField(help_text="Sharepoint folder ID", max_length=200),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "web_url",
                    models.URLField(
                        blank=True,
                        help_text="Direct URL to folder in Sharepoint",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "drive",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pwms.sharepointdrive",
                    ),
                ),
                (
                    "parent_folder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subfolders",
                        to="pwms.sharepointfolder",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pwms.sharepointsite",
                    ),
                ),
            ],
            options={
                "ordering": ["site", "drive", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("site", "drive", "folder_id"),
                        name="workflows_Sharepointfolder_site_drive_folder_uniq",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SharepointSiteMember",
            fields=[
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid7,
                        editable=False,
                        help_text="Public UUIDv7 identifier for external references and API routes.",
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pwms.sharepointsite",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("site", "user"),
                        name="workflows_sitemember_site_user_uniq",
                    )
                ],
            },
        ),
    ]
