# Generated by Django 6.1.1 on 2026-09-11 10:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("pwms", "0002_sharepointtoken_alter_group_group_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="state",
            name="public_name",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("in_progress", "In Progress"),
                    ("referred", "Referred"),
                    ("withdrawn", "Withdrawn"),
                    ("on_hold", "On Hold"),
                    ("cancelled", "Cancelled"),
                    ("closed", "Closed"),
                ],
                default="new",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="workflowtype",
            name="parent_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent workflow type this type nests under (a Delegation Report report type is the parent of the International Resolution type).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="child_types",
                to="pwms.workflowtype",
            ),
        ),
        migrations.CreateModel(
            name="DelegationReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid7,
                        editable=False,
                        help_text="Public UUIDv7 identifier for external references and API routes.",
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True)),
                ("deadline", models.DateTimeField(blank=True, null=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_assigned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "current_state",
                    models.ForeignKey(
                        help_text="Current workflow state. Must belong to ``workflow_type``.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_current",
                        to="pwms.state",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_owned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "referred_to_groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Groups this workflow is dynamically referred to",
                        related_name="%(class)s_referred",
                        to="pwms.group",
                    ),
                ),
                (
                    "workflow_type",
                    models.ForeignKey(
                        help_text="Reusable state machine (states/transitions) this instance follows.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_instances",
                        to="pwms.workflowtype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WorkflowRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid7,
                        editable=False,
                        help_text="Public UUIDv7 identifier for external references and API routes.",
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("parent_object_id", models.PositiveBigIntegerField()),
                ("child_object_id", models.PositiveBigIntegerField()),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("contains", "Contains"),
                            ("follows_up", "Follows Up"),
                            ("supersedes", "Supersedes"),
                            ("relates_to", "Relates To"),
                        ],
                        default="contains",
                        help_text="Nature of the link; a report normally *contains* its resolutions.",
                        max_length=30,
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Display order among siblings."
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "child_content_type",
                    models.ForeignKey(
                        help_text="Content type of the child workflow instance.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_child_links",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "parent_content_type",
                    models.ForeignKey(
                        help_text="Content type of the parent workflow instance.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_parent_links",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
                "indexes": [
                    models.Index(
                        fields=["parent_content_type", "parent_object_id"],
                        name="pwms_workfl_parent__184d7a_idx",
                    ),
                    models.Index(
                        fields=["child_content_type", "child_object_id"],
                        name="pwms_workfl_child_c_c351a3_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("child_content_type", "child_object_id"),
                        name="workflows_relationship_child_uniq",
                    )
                ],
            },
        ),
    ]
