# Generated by Django 6.1.1 on 2026-09-11 11:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pwms", "0003_state_public_name_workflowtype_parent_type_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="delegationreport",
            options={
                "verbose_name": "Delegation Report",
                "verbose_name_plural": "Delegation Reports",
            },
        ),
        migrations.AddField(
            model_name="delegationreport",
            name="atc_document_url",
            field=models.URLField(
                blank=True,
                help_text="SharePoint link to the ATC / update document (BR03.5.5).",
            ),
        ),
        migrations.AddField(
            model_name="delegationreport",
            name="atc_page_number",
            field=models.CharField(
                blank=True,
                help_text="ATC page where the update appears (BR03.5.3).",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="delegationreport",
            name="atc_publication_date",
            field=models.DateField(
                blank=True, help_text="ATC publication date (BR03.5.3).", null=True
            ),
        ),
        migrations.AddField(
            model_name="delegationreport",
            name="atc_reference",
            field=models.CharField(
                blank=True,
                help_text="ATC reference for the report update (BR03.5.3).",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="delegationreport",
            name="engagement_end_date",
            field=models.DateField(
                blank=True,
                help_text="Engagement end date; may not be before the start date or in the future (BR02.3.5).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="delegationreport",
            name="engagement_name",
            field=models.CharField(
                blank=True,
                help_text="Name of the international engagement / forum (BR02.3.3).",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="delegationreport",
            name="engagement_start_date",
            field=models.DateField(
                blank=True,
                help_text="Engagement start date; may not be a future date (BR02.3.4).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="delegationreport",
            name="location_city",
            field=models.CharField(
                blank=True,
                help_text="Engagement location – city (BR02.3.6).",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="delegationreport",
            name="location_country",
            field=models.CharField(
                blank=True,
                help_text="Engagement location – country (BR02.3.6).",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="delegationreport",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Additional notes / follow-up action by Presiding Officer(s) or Parliamentarian(s) (BR02.3.13).",
            ),
        ),
        migrations.AddField(
            model_name="delegationreport",
            name="reference_number",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="System-generated unique reference number (BR02.6).",
                max_length=30,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="delegationreport",
            name="report_document_url",
            field=models.URLField(
                blank=True,
                help_text="SharePoint link to the delegation report document (BR02.3.14).",
            ),
        ),
        migrations.AddField(
            model_name="internationalresolution",
            name="implementation_progress",
            field=models.TextField(
                blank=True,
                help_text="Latest narrative on Parliament's implementation of the resolution.",
            ),
        ),
        migrations.AddField(
            model_name="internationalresolution",
            name="resolution_text",
            field=models.TextField(
                blank=True,
                help_text="Resolution as concluded, captured from the delegation report recommendations (BR02.3.9).",
            ),
        ),
        migrations.AddField(
            model_name="internationalresolution",
            name="responsible_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Committee / group responsible for implementation.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolutions_responsible",
                to="pwms.group",
            ),
        ),
        migrations.AlterField(
            model_name="state",
            name="public_name",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("in_progress", "In Progress"),
                    ("referred", "Referred"),
                    ("withdrawn", "Withdrawn"),
                    ("on_hold", "On Hold"),
                    ("cancelled", "Cancelled"),
                    ("implemented", "Implemented"),
                    ("closed", "Closed"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="DelegationParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid7,
                        editable=False,
                        help_text="Public UUIDv7 identifier for external references and API routes.",
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "participant_type",
                    models.CharField(
                        choices=[
                            ("member", "Parliamentary Delegation Member"),
                            ("official", "Support Official"),
                        ],
                        default="member",
                        help_text="Parliamentary delegation member or support official.",
                        max_length=20,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Honorific / job title, e.g. Hon., Dr, Prof.",
                        max_length=50,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "delegation_role",
                    models.CharField(
                        blank=True,
                        help_text="Role in the delegation, e.g. Leader of the Delegation, MP, Secretary.",
                        max_length=100,
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Display order within the delegation."
                    ),
                ),
                (
                    "delegation_report",
                    models.ForeignKey(
                        help_text="Delegation report this person is attached to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="pwms.delegationreport",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional link to the person's system account.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delegation_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["participant_type", "order", "last_name", "first_name"],
                "indexes": [
                    models.Index(
                        fields=["delegation_report", "participant_type"],
                        name="pwms_delega_delegat_1b893a_idx",
                    )
                ],
            },
        ),
    ]
