# Generated by Django 6.1.1 on 2026-09-11 11:54

import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("pwms", "0005_seed_workflow_definitions"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid7,
                        editable=False,
                        help_text="Public UUIDv7 identifier for external references and API routes.",
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True, editable=False, populate_from="name", unique=True
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "is_system",
                    models.BooleanField(
                        default=False,
                        help_text="Seeded standard type; treated as read-only in the admin.",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="transition",
            name="required_event_types",
            field=models.ManyToManyField(
                blank=True,
                help_text="Transitions are blocked until at least one event of each selected type has been recorded on the workflow instance.",
                related_name="required_by_transitions",
                to="pwms.eventtype",
            ),
        ),
        migrations.CreateModel(
            name="WorkflowEvent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("object_id", models.PositiveBigIntegerField()),
                (
                    "occurred_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the event happened.",
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("system", "System"),
                            ("integration", "Integration"),
                        ],
                        default="user",
                        max_length=20,
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Event-specific structured detail.",
                    ),
                ),
                (
                    "document_url",
                    models.URLField(
                        blank=True,
                        help_text="Optional SharePoint / document reference.",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who caused the event (null for system-generated events).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "event_type",
                    models.ForeignKey(
                        help_text="What happened.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="pwms.eventtype",
                    ),
                ),
                (
                    "transition_log",
                    models.ForeignKey(
                        blank=True,
                        help_text="State change that produced this event, when applicable.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="pwms.transitionlog",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id", "-occurred_at"],
                        name="pwms_workfl_content_69a949_idx",
                    ),
                    models.Index(
                        fields=["event_type", "-occurred_at"],
                        name="pwms_workfl_event_t_7cebab_idx",
                    ),
                ],
            },
        ),
    ]
