# Generated by Django 6.1.1 on 2026-09-11 11:59

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("pwms", "0007_seed_event_types"),
    ]

    operations = [
        migrations.CreateModel(
            name="DelegationReportUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid7,
                        editable=False,
                        help_text="Public UUIDv7 identifier for external references and API routes.",
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "update_date",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        help_text="Date of the update (BR03.5.2).",
                    ),
                ),
                (
                    "atc_reference",
                    models.CharField(
                        blank=True,
                        help_text="ATC reference (BR03.5.3).",
                        max_length=255,
                    ),
                ),
                (
                    "atc_publication_date",
                    models.DateField(
                        blank=True,
                        help_text="ATC publication date (BR03.5.3).",
                        null=True,
                    ),
                ),
                (
                    "atc_page_number",
                    models.CharField(
                        blank=True,
                        help_text="ATC page number (BR03.5.3).",
                        max_length=50,
                    ),
                ),
                (
                    "atc_document_url",
                    models.URLField(
                        blank=True,
                        help_text="SharePoint link to the ATC / update document (BR03.5.5).",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "delegation_report",
                    models.ForeignKey(
                        help_text="Report this update belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updates",
                        to="pwms.delegationreport",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delegation_report_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resulting_state",
                    models.ForeignKey(
                        blank=True,
                        help_text="Report status (update type) after this update (BR03.5.1).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delegation_report_updates",
                        to="pwms.state",
                    ),
                ),
            ],
            options={
                "ordering": ["-update_date", "-id"],
                "indexes": [
                    models.Index(
                        fields=["delegation_report", "-update_date"],
                        name="pwms_delega_delegat_7fee79_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TransitionCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid7,
                        editable=False,
                        help_text="Public UUIDv7 identifier for external references and API routes.",
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "condition_type",
                    models.CharField(
                        choices=[
                            ("no_open_referrals", "No open referrals"),
                            ("all_children_closed", "All child workflows are terminal"),
                            ("field_set", "Required field is set"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        blank=True,
                        help_text="Field checked by parameterised conditions, e.g. field_set.",
                        max_length=100,
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck to temporarily disable the rule.",
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                (
                    "transition",
                    models.ForeignKey(
                        help_text="Transition this rule guards.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conditions",
                        to="pwms.transition",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("transition", "condition_type", "field_name"),
                        name="workflows_transitioncondition_uniq",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WorkflowReferral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid7,
                        editable=False,
                        help_text="Public UUIDv7 identifier for external references and API routes.",
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("object_id", models.PositiveBigIntegerField()),
                (
                    "referred_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "due_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Response deadline for the referral.",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("responded", "Responded"),
                            ("recalled", "Recalled"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("response_document_url", models.URLField(blank=True)),
                ("response_notes", models.TextField(blank=True)),
                ("recalled_at", models.DateTimeField(blank=True, null=True)),
                ("recall_reason", models.TextField(blank=True)),
                (
                    "deadline_notified_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last deadline reminder sent (for the scheduled job).",
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "recalled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workflow_referrals_recalled",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "referred_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workflow_referrals_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "referred_to",
                    models.ForeignKey(
                        help_text="Committee / group asked to consider the workflow.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workflow_referrals",
                        to="pwms.group",
                    ),
                ),
                (
                    "responded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workflow_referrals_responded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-referred_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id", "-referred_at"],
                        name="pwms_workfl_content_7a56e7_idx",
                    ),
                    models.Index(
                        fields=["status", "due_date"],
                        name="pwms_workfl_status_f39dcb_idx",
                    ),
                ],
            },
        ),
    ]
