# Generated by Django 6.1.1 on 2026-09-11 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pwms", "0009_backfill_referrals_and_atc_updates"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="delegationreport",
            name="atc_document_url",
        ),
        migrations.RemoveField(
            model_name="delegationreport",
            name="atc_page_number",
        ),
        migrations.RemoveField(
            model_name="delegationreport",
            name="atc_publication_date",
        ),
        migrations.RemoveField(
            model_name="delegationreport",
            name="atc_reference",
        ),
        migrations.RemoveField(
            model_name="delegationreport",
            name="referred_to_groups",
        ),
        migrations.RemoveField(
            model_name="internationalresolution",
            name="referred_to_groups",
        ),
    ]
