# Generated by Django 6.1.1 on 2026-09-11 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pwms", "0010_remove_delegationreport_atc_document_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowtype",
            name="create_roles",
            field=models.ManyToManyField(
                blank=True,
                help_text="Roles from this type's group that may create workflow instances. Leave empty to let only superusers create instances.",
                related_name="creatable_workflow_types",
                to="pwms.role",
            ),
        ),
        migrations.AddField(
            model_name="workflowtype",
            name="group",
            field=models.ForeignKey(
                help_text="Group whose members and roles govern this workflow type.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="workflow_types",
                to="pwms.group",
            ),
        ),
    ]
