# Generated by Django 6.1.1 on 2026-09-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pwms", "0012_assign_workflow_type_rbac_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowgroupaccess",
            name="can_comment",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="workflowgroupaccess",
            name="can_manage",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="workflowgroupaccess",
            name="can_share",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="workflowrolepermission",
            name="can_comment",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="workflowrolepermission",
            name="can_manage",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="workflowrolepermission",
            name="can_share",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="workflowstatepermission",
            name="can_comment",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="workflowstatepermission",
            name="can_manage",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="workflowstatepermission",
            name="can_share",
            field=models.BooleanField(default=False),
        ),
    ]
