# Generated by Django 6.1.1 on 2026-09-11 23:44
"""Country/city reference tables, and the delegation location foreign keys.

``location_city``/``location_country`` were free-text columns, so they are
dropped and re-created as foreign keys instead of being cast in place (Postgres
cannot cast the empty strings they held to ``bigint``). Nothing is lost: no
report had a location recorded, and the place tables stay empty until
``manage.py load_places`` runs.
"""

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pwms", "0013_workflowgroupaccess_can_comment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid7,
                        editable=False,
                        help_text="Public UUIDv7 identifier for external references and API routes.",
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "ascii_name",
                    models.CharField(
                        blank=True,
                        help_text="Diacritic-free spelling, searched alongside the name.",
                        max_length=200,
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "population",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Used to rank search results; 0 when the source has no figure.",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "cities",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid7,
                        editable=False,
                        help_text="Public UUIDv7 identifier for external references and API routes.",
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        help_text="ISO 3166-1 alpha-2 code, e.g. ZA.",
                        max_length=2,
                        unique=True,
                    ),
                ),
                (
                    "iso3",
                    models.CharField(
                        blank=True, help_text="ISO 3166-1 alpha-3.", max_length=3
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=100)),
                ("continent", models.CharField(blank=True, max_length=2)),
            ],
            options={
                "verbose_name_plural": "countries",
                "ordering": ["name"],
            },
        ),
        migrations.RemoveField(
            model_name="delegationreport",
            name="location_city",
        ),
        migrations.RemoveField(
            model_name="delegationreport",
            name="location_country",
        ),
        migrations.AddField(
            model_name="delegationreport",
            name="location_city",
            field=models.ForeignKey(
                blank=True,
                help_text="Engagement location – city (BR02.3.6).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="delegation_reports",
                to="pwms.city",
            ),
        ),
        migrations.AddField(
            model_name="city",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cities",
                to="pwms.country",
            ),
        ),
        migrations.AddField(
            model_name="delegationreport",
            name="location_country",
            field=models.ForeignKey(
                blank=True,
                help_text="Engagement location – country (BR02.3.6).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="delegation_reports",
                to="pwms.country",
            ),
        ),
        migrations.AddIndex(
            model_name="city",
            index=models.Index(
                fields=["country", "name"], name="pwms_city_country_77382c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="city",
            index=models.Index(
                fields=["country", "ascii_name"], name="pwms_city_country_d8479a_idx"
            ),
        ),
    ]
