# Generated by Django 6.1.1 on 2026-09-14 12:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pwms", "0014_city_country_alter_delegationreport_location_city_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InternationalAgreement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid7,
                        editable=False,
                        help_text="Public UUIDv7 identifier for external references and API routes.",
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True)),
                ("deadline", models.DateTimeField(blank=True, null=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="System-generated unique reference number (BR02).",
                        max_length=30,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "agreement_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("section-231-2", "Section 231(2) agreement"),
                            ("section-231-3", "Section 231(3) agreement"),
                        ],
                        help_text="Constitutional basis of the agreement (BR02).",
                        max_length=20,
                    ),
                ),
                (
                    "submitting_department",
                    models.CharField(
                        blank=True,
                        help_text="Government department that submitted the agreement (BR02).",
                        max_length=255,
                    ),
                ),
                (
                    "responsible_minister",
                    models.CharField(
                        blank=True,
                        help_text="Responsible Member of the Executive (Minister) submitting the agreement (BR02).",
                        max_length=255,
                    ),
                ),
                (
                    "atc_tabling_date",
                    models.DateField(
                        blank=True,
                        help_text="Date the agreement was tabled in the ATC (BR02).",
                        null=True,
                    ),
                ),
                (
                    "atc_reference",
                    models.CharField(
                        blank=True,
                        help_text="Reference details of the ATC and any other relevant documents (BR02).",
                        max_length=255,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes / follow-up action by Presiding Officer(s) or Parliamentarian(s) (BR02).",
                    ),
                ),
                (
                    "agreement_document_url",
                    models.URLField(
                        blank=True,
                        help_text="SharePoint link to the uploaded agreement document (BR02).",
                    ),
                ),
                (
                    "explanatory_memorandum_url",
                    models.URLField(
                        blank=True,
                        help_text="SharePoint link to the explanatory memorandum (BR02).",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_assigned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "current_state",
                    models.ForeignKey(
                        help_text="Current workflow state. Must belong to ``workflow_type``.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_current",
                        to="pwms.state",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_owned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "referral_committees",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Committee(s) to which the agreement is referred (BR02).",
                        related_name="international_agreements_referred",
                        to="pwms.group",
                    ),
                ),
                (
                    "workflow_type",
                    models.ForeignKey(
                        help_text="Reusable state machine (states/transitions) this instance follows.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_instances",
                        to="pwms.workflowtype",
                    ),
                ),
            ],
            options={
                "verbose_name": "International Agreement",
                "verbose_name_plural": "International Agreements",
            },
        ),
    ]
