# Generated by Django 6.1.1 on 2026-09-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pwms", "0016_seed_international_agreement_workflow"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowtype",
            name="viewer_groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="Read-only stakeholder groups (an interest in the workflow but no active role). Every new instance of this type is shared with these groups at view level when it is created.",
                related_name="viewer_workflow_types",
                to="pwms.group",
            ),
        ),
    ]
