# Generated by Django 6.1.1 on 2026-09-14 13:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pwms", "0017_workflowtype_viewer_groups"),
    ]

    operations = [
        migrations.AlterField(
            model_name="state",
            name="public_name",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("in_progress", "In Progress"),
                    ("referred", "Referred"),
                    ("withdrawn", "Withdrawn"),
                    ("on_hold", "On Hold"),
                    ("cancelled", "Cancelled"),
                    ("implemented", "Implemented"),
                    ("closed", "Closed"),
                    ("introduced", "Introduced"),
                    ("under_consideration", "Under Parliamentary Consideration"),
                    ("ncop", "National Council of Provinces"),
                    ("mediation", "Mediation / Reconsideration"),
                    ("awaiting_assent", "Awaiting Presidential Assent"),
                    ("signed_into_law", "Signed into Law"),
                    ("constitutional_review", "Referred Back / Constitutional Review"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid7,
                        editable=False,
                        help_text="Public UUIDv7 identifier for external references and API routes.",
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True)),
                ("deadline", models.DateTimeField(blank=True, null=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "bill_number",
                    models.CharField(
                        help_text="Parliamentary B-number, including any version suffix (BRS §13.1).",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "short_title",
                    models.CharField(
                        blank=True,
                        help_text="Short title of the bill (BRS §7A).",
                        max_length=255,
                    ),
                ),
                (
                    "bill_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "section-74",
                                "Section 74 bill (constitutional amendment)",
                            ),
                            ("section-75", "Section 75 bill (ordinary)"),
                            ("section-76", "Section 76 bill (affecting provinces)"),
                            ("section-77", "Section 77 bill (money)"),
                        ],
                        help_text="Constitutional classification: Section 74, 75, 76 or 77 (BRS §13.1).",
                        max_length=20,
                    ),
                ),
                (
                    "house_of_origin",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("na", "National Assembly"),
                            ("ncop", "National Council of Provinces"),
                        ],
                        help_text="House of introduction (BRS §7A).",
                        max_length=10,
                    ),
                ),
                (
                    "sponsor",
                    models.CharField(
                        blank=True,
                        help_text="Sponsor or originating authority (BRS §7A).",
                        max_length=255,
                    ),
                ),
                (
                    "introduced_date",
                    models.DateField(
                        blank=True,
                        help_text="Date the bill was introduced (BRS §13.1).",
                        null=True,
                    ),
                ),
                (
                    "current_version",
                    models.CharField(
                        blank=True,
                        help_text="Latest bill version label; earlier versions remain in the audit trail (BRS §15A).",
                        max_length=100,
                    ),
                ),
                (
                    "atc_reference",
                    models.CharField(
                        blank=True,
                        help_text="ATC reference for the bill's movements (BRS §7B).",
                        max_length=255,
                    ),
                ),
                (
                    "order_paper_reference",
                    models.CharField(
                        blank=True,
                        help_text="Order paper reference, where available (BRS §7B).",
                        max_length=255,
                    ),
                ),
                (
                    "bill_document_url",
                    models.URLField(
                        blank=True,
                        help_text="SharePoint link to the bill document (BRS §7B).",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Sub-events or explanatory notes under the current stage (BRS §15A).",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_assigned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "current_state",
                    models.ForeignKey(
                        help_text="Current workflow state. Must belong to ``workflow_type``.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_current",
                        to="pwms.state",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_owned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "responsible_committee",
                    models.ForeignKey(
                        blank=True,
                        help_text="Committee responsible for the bill (BRS §13.2).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bills_responsible",
                        to="pwms.group",
                    ),
                ),
                (
                    "workflow_type",
                    models.ForeignKey(
                        help_text="Reusable state machine (states/transitions) this instance follows.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_instances",
                        to="pwms.workflowtype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bill",
                "verbose_name_plural": "Bills",
            },
        ),
    ]
