# Generated by Django 6.1.1 on 2026-09-14 14:06

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pwms", "0019_seed_bill_workflow"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bill",
            name="current_version",
        ),
        migrations.CreateModel(
            name="BillVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid7,
                        editable=False,
                        help_text="Public UUIDv7 identifier for external references and API routes.",
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "version_label",
                    models.CharField(
                        help_text="Version label, including the B-number suffix where it changed (e.g. 'B 12—2026 (1st amendment)').",
                        max_length=100,
                    ),
                ),
                (
                    "version_type",
                    models.CharField(
                        choices=[
                            ("introduced", "Introduced version"),
                            ("amended", "Amended bill"),
                            ("amendment_schedule", "Amendment schedule"),
                        ],
                        default="introduced",
                        help_text="Introduced bill, amended bill or amendment schedule (BRS §15A).",
                        max_length=20,
                    ),
                ),
                (
                    "version_date",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        help_text="Date this version was tabled / published.",
                    ),
                ),
                (
                    "document_url",
                    models.URLField(
                        blank=True,
                        help_text="SharePoint link to this version's document (BRS §7B).",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="What changed in this version."
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        default=False,
                        help_text="Mark the version currently before Parliament.",
                    ),
                ),
                (
                    "bill",
                    models.ForeignKey(
                        help_text="Bill this version belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="pwms.bill",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who recorded this version (BRS §7A contributor accountability).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bill_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-version_date", "-id"],
                "indexes": [
                    models.Index(
                        fields=["bill", "-version_date"],
                        name="pwms_billve_bill_id_0d693f_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_current", True)),
                        fields=("bill",),
                        name="workflows_billversion_one_current_per_bill_uniq",
                    )
                ],
            },
        ),
    ]
