# Generated by Django 6.1.1 on 2026-09-15 14:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("pwms", "0025_delegation_participant_unique_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid7,
                        editable=False,
                        help_text="Public UUIDv7 identifier for external references and API routes.",
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel",
                    models.CharField(
                        choices=[("in_app", "In-app"), ("email", "Email")],
                        max_length=10,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("workflow-created", "Workflow created"),
                            ("workflow-transition", "Workflow transitioned"),
                            ("referral-created", "Referral raised"),
                            ("referral-responded", "Referral answered"),
                            ("referral-recalled", "Referral recalled"),
                            ("referral-expired", "Referral expired"),
                            ("referral-deadline", "Referral deadline reminder"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                (
                    "body",
                    models.TextField(
                        blank=True,
                        help_text="Rendered exactly as it was (or would be) sent.",
                    ),
                ),
                ("url", models.CharField(blank=True, max_length=500)),
                ("object_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("context", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "error",
                    models.TextField(
                        blank=True, help_text="Delivery failure, when there is one."
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Triggering user, when there is one.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications_triggered",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        help_text="Who is being told.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "read_at"],
                        name="pwms_notifi_recipie_b6d00a_idx",
                    ),
                    models.Index(
                        fields=["recipient", "-created_at"],
                        name="pwms_notifi_recipie_3a59f1_idx",
                    ),
                ],
            },
        ),
    ]
