# Generated by Django 6.1.1 on 2026-09-15 17:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("pwms", "0026_notification"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid7,
                        editable=False,
                        help_text="Public UUIDv7 identifier for external references and API routes.",
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("object_id", models.CharField(blank=True, max_length=64, null=True)),
                ("name", models.CharField(max_length=500)),
                (
                    "drive_id",
                    models.CharField(help_text="SharePoint drive ID", max_length=512),
                ),
                (
                    "item_id",
                    models.CharField(help_text="SharePoint item ID", max_length=512),
                ),
                (
                    "mimetype",
                    models.CharField(
                        blank=True,
                        help_text="MIME type of the file",
                        max_length=512,
                        null=True,
                    ),
                ),
                (
                    "size",
                    models.BigIntegerField(
                        blank=True, help_text="File size in bytes", null=True
                    ),
                ),
                (
                    "download_url",
                    models.URLField(
                        blank=True,
                        help_text="SharePoint download URL",
                        max_length=2048,
                        null=True,
                    ),
                ),
                (
                    "sharepoint_web_url",
                    models.URLField(
                        blank=True,
                        help_text="Direct SharePoint web URL",
                        max_length=2048,
                        null=True,
                    ),
                ),
                (
                    "sharepoint_folder_path",
                    models.CharField(
                        blank=True,
                        help_text="Folder path in SharePoint",
                        max_length=500,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("response", "Response"),
                            ("document", "Document"),
                            ("petition", "Petition"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "sharepoint_drive",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pwms.sharepointdrive",
                    ),
                ),
                (
                    "sharepoint_folder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pwms.sharepointfolder",
                    ),
                ),
                (
                    "sharepoint_site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pwms.sharepointsite",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="pwms_attach_content_0aee1f_idx",
                    ),
                    models.Index(
                        fields=["sharepoint_site", "sharepoint_drive"],
                        name="pwms_attach_sharepo_633daf_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("content_type", "object_id", "item_id"),
                        name="workflows_attachment_object_item_uniq",
                    )
                ],
            },
        ),
    ]
