# Generated by Django 6.1.1 on 2026-09-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pwms", "0027_attachment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="type",
            field=models.CharField(
                choices=[
                    ("agenda", "Agenda"),
                    ("agreement", "Agreement"),
                    ("annexure", "Annexure"),
                    ("bill", "Bill"),
                    ("brief", "Brief"),
                    ("correspondence", "Correspondence"),
                    ("document", "Document"),
                    ("draft", "Draft"),
                    ("gazette", "Gazette"),
                    ("memorandum", "Memorandum"),
                    ("minutes", "Minutes"),
                    ("motion", "Motion"),
                    ("notice", "Notice"),
                    ("order_paper", "Order Paper"),
                    ("other", "Other"),
                    ("petition", "Petition"),
                    ("presentation", "Presentation"),
                    ("question", "Question"),
                    ("report", "Report"),
                    ("resolution", "Resolution"),
                    ("response", "Response"),
                    ("speech", "Speech"),
                    ("submission", "Submission"),
                    ("transcript", "Transcript"),
                ],
                max_length=50,
            ),
        ),
    ]
