# Generated by Django 6.1.1 on 2026-09-15 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pwms", "0028_alter_attachment_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="sharepointsite",
            name="enabled",
            field=models.BooleanField(
                default=True,
                help_text="Uncheck to hide this site (and its drives) from the attachment picker.",
            ),
        ),
    ]
