# Generated by Django 6.1.1 on 2026-09-15 18:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pwms", "0029_sharepointsite_enabled"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttachmentVersion",
            fields=[
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid7,
                        editable=False,
                        help_text="Public UUIDv7 identifier for external references and API routes.",
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version_id",
                    models.CharField(
                        help_text="SharePoint version ID, e.g. 2.0", max_length=128
                    ),
                ),
                (
                    "size",
                    models.BigIntegerField(
                        blank=True,
                        help_text="File size in bytes at this version",
                        null=True,
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When SharePoint saved this version",
                        null=True,
                    ),
                ),
                (
                    "modified_by",
                    models.CharField(
                        blank=True,
                        help_text="Who saved this version, as reported by SharePoint",
                        max_length=512,
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        default=False,
                        help_text="The version currently held by SharePoint",
                    ),
                ),
                (
                    "attachment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="pwms.attachment",
                    ),
                ),
            ],
            options={
                "ordering": ["-modified_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["attachment", "-modified_at"],
                        name="pwms_attach_attachm_0ea186_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("attachment", "version_id"),
                        name="workflows_attachmentversion_version_uniq",
                    )
                ],
            },
        ),
    ]
