# Generated by Django 6.1.1 on 2026-09-15 19:27

import django.db.models.deletion
import pwms.models.reports
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pwms", "0031_seed_attachment_event_types"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid7,
                        editable=False,
                        help_text="Public UUIDv7 identifier for external references and API routes.",
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "token",
                    models.CharField(
                        db_index=True,
                        default=pwms.models.reports.generate_token,
                        editable=False,
                        help_text="Unguessable URL token the share is opened with.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Human label for the share (defaults to the report title).",
                        max_length=255,
                    ),
                ),
                (
                    "filters",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Report filter values the share was created with.",
                    ),
                ),
                (
                    "recipients",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated email addresses the link was sent to.",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True, help_text="Note sent alongside the link."
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the link stops working (null = never).",
                        null=True,
                    ),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True, help_text="When the link was withdrawn.", null=True
                    ),
                ),
                ("access_count", models.PositiveIntegerField(default=0)),
                ("last_accessed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who created the share.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="report_shares",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["created_by", "-created_at"],
                        name="pwms_report_created_dccee5_idx",
                    )
                ],
            },
        ),
    ]
