# Generated by Django 6.1.1 on 2026-09-15 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pwms", "0032_reportshare"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportshare",
            name="last_error",
            field=models.TextField(
                blank=True, help_text="Why the last scheduled send failed, if it did."
            ),
        ),
        migrations.AddField(
            model_name="reportshare",
            name="last_sent_at",
            field=models.DateTimeField(
                blank=True, help_text="When a scheduled send last ran.", null=True
            ),
        ),
        migrations.AddField(
            model_name="reportshare",
            name="next_send_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the next scheduled send falls due.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="reportshare",
            name="schedule",
            field=models.CharField(
                choices=[
                    ("none", "Do not repeat"),
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                ],
                default="none",
                help_text="How often to re-email this report; 'none' sends it once.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="reportshare",
            name="schedule_format",
            field=models.CharField(
                blank=True,
                choices=[
                    ("xlsx", "Excel workbook (.xlsx)"),
                    ("pdf", "PDF document (.pdf)"),
                    ("html", "Web page (.html)"),
                    ("csv", "Comma-separated values (.csv)"),
                ],
                help_text="Document to attach to each scheduled send (blank = link only).",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="reportshare",
            name="send_count",
            field=models.PositiveIntegerField(
                default=0, help_text="How many scheduled sends have run."
            ),
        ),
        migrations.AddIndex(
            model_name="reportshare",
            index=models.Index(
                fields=["schedule", "next_send_at"],
                name="pwms_report_schedul_afd2c4_idx",
            ),
        ),
    ]
