# Generated by Django 6.1.1 on 2026-09-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pwms", "0033_reportshare_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="attempts",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Delivery attempts made so far (the queue retries a failure).",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="error",
            field=models.TextField(
                blank=True,
                help_text="Delivery failure: the last attempt while the row is still pending, or the reason it was given up on.",
            ),
        ),
    ]
