# Generated by Django 6.1.1 on 2026-09-16 17:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("pwms", "0034_notification_attempts"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid7,
                        editable=False,
                        help_text="Public UUIDv7 identifier for external references and API routes.",
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("object_id", models.PositiveBigIntegerField()),
                (
                    "body",
                    models.TextField(
                        help_text="What was noted: a decision, a follow-up, a conversation."
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who recorded the note.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workflow_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id", "-created_at"],
                        name="pwms_workfl_content_31daac_idx",
                    )
                ],
            },
        ),
    ]
