# Generated by Django 6.1.1 on 2026-09-16 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pwms", "0035_workflownote"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="delegationparticipant",
            name="workflows_participant_report_user_uniq",
        ),
        migrations.AddField(
            model_name="delegationparticipant",
            name="removed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the person was taken off the delegation.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="delegationparticipant",
            name="removed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Who took them off the delegation.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="delegation_participants_removed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="delegationparticipant",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("removed_at__isnull", True), ("user__isnull", False)
                ),
                fields=("delegation_report", "user"),
                name="workflows_participant_report_user_uniq",
            ),
        ),
    ]
