# Generated by Django 6.1.1 on 2026-09-27 18:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pwms', '0046_seed_irpd_create_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegationreport',
            name='engagement_end_date',
            field=models.DateField(blank=True, help_text='Engagement end date; may not be before the start date or in the future.', null=True),
        ),
        migrations.AlterField(
            model_name='delegationreport',
            name='engagement_name',
            field=models.CharField(blank=True, help_text='Name of the international engagement / forum.', max_length=255),
        ),
        migrations.AlterField(
            model_name='delegationreport',
            name='engagement_start_date',
            field=models.DateField(blank=True, help_text='Engagement start date; may not be a future date.', null=True),
        ),
        migrations.AlterField(
            model_name='delegationreport',
            name='location_city',
            field=models.ForeignKey(blank=True, help_text='Engagement location – city.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegation_reports', to='pwms.city'),
        ),
        migrations.AlterField(
            model_name='delegationreport',
            name='location_country',
            field=models.ForeignKey(blank=True, help_text='Engagement location – country.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegation_reports', to='pwms.country'),
        ),
        migrations.AlterField(
            model_name='delegationreport',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes / follow-up action by Presiding Officer(s) or Parliamentarian(s).'),
        ),
        migrations.AlterField(
            model_name='delegationreport',
            name='reference_number',
            field=models.CharField(blank=True, editable=False, help_text='System-generated unique reference number.', max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='delegationreport',
            name='report_document_url',
            field=models.URLField(blank=True, help_text='SharePoint link to the delegation report document.', max_length=2048),
        ),
        migrations.AlterField(
            model_name='delegationreportupdate',
            name='atc_document_url',
            field=models.URLField(blank=True, help_text='SharePoint link to the ATC / update document.', max_length=2048),
        ),
        migrations.AlterField(
            model_name='delegationreportupdate',
            name='atc_page_number',
            field=models.CharField(blank=True, help_text='ATC page number.', max_length=50),
        ),
        migrations.AlterField(
            model_name='delegationreportupdate',
            name='atc_publication_date',
            field=models.DateField(blank=True, help_text='ATC publication date.', null=True),
        ),
        migrations.AlterField(
            model_name='delegationreportupdate',
            name='atc_reference',
            field=models.CharField(blank=True, help_text='ATC reference.', max_length=255),
        ),
        migrations.AlterField(
            model_name='delegationreportupdate',
            name='resulting_state',
            field=models.ForeignKey(blank=True, help_text='Report status (update type) after this update.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delegation_report_updates', to='pwms.state'),
        ),
        migrations.AlterField(
            model_name='delegationreportupdate',
            name='update_date',
            field=models.DateField(default=django.utils.timezone.localdate, help_text='Date of the update.'),
        ),
        migrations.AlterField(
            model_name='internationalagreement',
            name='agreement_document_url',
            field=models.URLField(blank=True, help_text='SharePoint link to the uploaded agreement document.', max_length=2048),
        ),
        migrations.AlterField(
            model_name='internationalagreement',
            name='agreement_type',
            field=models.CharField(blank=True, choices=[('section-231-2', 'Section 231(2) agreement'), ('section-231-3', 'Section 231(3) agreement')], help_text='Constitutional basis of the agreement.', max_length=20),
        ),
        migrations.AlterField(
            model_name='internationalagreement',
            name='atc_reference',
            field=models.CharField(blank=True, help_text='Reference details of the ATC and any other relevant documents.', max_length=255),
        ),
        migrations.AlterField(
            model_name='internationalagreement',
            name='atc_tabling_date',
            field=models.DateField(blank=True, help_text='Date the agreement was tabled in the ATC.', null=True),
        ),
        migrations.AlterField(
            model_name='internationalagreement',
            name='explanatory_memorandum_url',
            field=models.URLField(blank=True, help_text='SharePoint link to the explanatory memorandum.', max_length=2048),
        ),
        migrations.AlterField(
            model_name='internationalagreement',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes / follow-up action by Presiding Officer(s) or Parliamentarian(s).'),
        ),
        migrations.AlterField(
            model_name='internationalagreement',
            name='reference_number',
            field=models.CharField(blank=True, editable=False, help_text='System-generated unique reference number.', max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='internationalagreement',
            name='referral_committees',
            field=models.ManyToManyField(blank=True, help_text='Committee(s) to which the agreement is referred.', related_name='international_agreements_referred', to='pwms.group'),
        ),
        migrations.AlterField(
            model_name='internationalagreement',
            name='responsible_minister',
            field=models.ForeignKey(blank=True, help_text='Responsible Member of the Executive (Minister) submitting the agreement.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_agreements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='internationalagreement',
            name='responsible_minister_name',
            field=models.CharField(blank=True, help_text='Minister as recorded on the tabled document - for a former office holder or one without a PWMS account.', max_length=255),
        ),
        migrations.AlterField(
            model_name='internationalagreement',
            name='submitting_department',
            field=models.CharField(blank=True, help_text='Government department that submitted the agreement.', max_length=255),
        ),
        migrations.AlterField(
            model_name='internationalresolution',
            name='resolution_text',
            field=models.TextField(blank=True, help_text='Resolution as concluded, captured from the delegation report recommendations.'),
        ),
    ]
