# Generated by Django 6.1.1 on 2026-09-09 14:55

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
import mptt.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid7,
                        editable=False,
                        help_text="Public UUIDv7 identifier for external references and API routes.",
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True, editable=False, populate_from="name", unique=True
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("can_transition_workflows", models.BooleanField(default=False)),
                ("can_create_workflows", models.BooleanField(default=False)),
                ("can_assign_workflows", models.BooleanField(default=False)),
                ("can_manage_permissions", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid7,
                        editable=False,
                        help_text="Public UUIDv7 identifier for external references and API routes.",
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True,
                        editable=False,
                        help_text="Stable internal identifier for this state (unique per workflow type).",
                        populate_from="name",
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "is_initial",
                    models.BooleanField(
                        default=False, help_text="Is this the initial state?"
                    ),
                ),
                (
                    "is_terminal",
                    models.BooleanField(
                        default=False, help_text="Is this a final state?"
                    ),
                ),
                (
                    "allows_referrals",
                    models.BooleanField(
                        default=True,
                        help_text="Can workflows in this state be referred to other groups?",
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                (
                    "color",
                    models.CharField(
                        default="#5b8f22", help_text="Hex color code", max_length=7
                    ),
                ),
            ],
            options={
                "ordering": ["workflow_type", "order", "name"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid7,
                        editable=False,
                        help_text="Public UUIDv7 identifier for external references and API routes.",
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True, editable=False, populate_from="name", unique=True
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck to prevent creating new workflow instances of this type.",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid7,
                        editable=False,
                        help_text="Public UUIDv7 identifier for external references and API routes.",
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True, editable=False, populate_from="name", unique=True
                    ),
                ),
                ("short_name", models.CharField(blank=True, max_length=50)),
                (
                    "group_type",
                    models.CharField(
                        choices=[
                            ("legislature", "Legislature"),
                            ("house", "House"),
                            ("portfolio_committee", "Portfolio Committee"),
                            ("select_committee", "Select Committee"),
                            ("special_committee", "Special Committee"),
                            ("public_accounts_committee", "Public Accounts Committee"),
                            ("internal_committee", "Internal Committee"),
                            ("ad_hoc_committee", "Ad Hoc Committee"),
                            ("joint_committee", "Joint Committee"),
                            ("administration", "Administration"),
                            ("office", "Office"),
                            ("division", "Division"),
                            ("section", "Section"),
                            ("business_unit", "Business Unit"),
                            ("party", "Party"),
                            ("executive", "Executive"),
                            ("presidency", "Presidency"),
                            ("ministry", "Ministry"),
                            ("department", "Department"),
                            ("province", "Province"),
                            ("premier", "Premier"),
                            ("delegation", "Delegation"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
                (
                    "parent",
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="pwms.group",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid7,
                        editable=False,
                        help_text="Public UUIDv7 identifier for external references and API routes.",
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("mr", "Mr."),
                            ("ms", "Ms."),
                            ("mrs", "Mrs."),
                            ("dr", "Dr."),
                            ("prof", "Prof."),
                            ("hon", "Hon."),
                            ("rt_hon", "Rt. Hon."),
                        ],
                        max_length=30,
                    ),
                ),
                ("middle_name", models.CharField(blank=True, max_length=100)),
                (
                    "employee_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("staff", "Staff"),
                            ("member", "Member"),
                            ("graduate", "Graduate"),
                        ],
                        max_length=10,
                    ),
                ),
                ("positiondesc", models.CharField(blank=True, max_length=100)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("idno_encrypted", models.TextField(blank=True)),
                (
                    "idno_hmac",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True, unique=True
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("bio", models.TextField(blank=True)),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="avatars/"),
                ),
                (
                    "is_mp",
                    models.BooleanField(
                        default=False, help_text="Is this user a Member of Parliament?"
                    ),
                ),
                (
                    "is_staff_member",
                    models.BooleanField(
                        default=False, help_text="Is this user a staff member?"
                    ),
                ),
                ("constituency", models.CharField(blank=True, max_length=200)),
                ("party_affiliation", models.CharField(blank=True, max_length=100)),
                ("date_joined_parliament", models.DateField(blank=True, null=True)),
                ("termination_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pwms.group",
                    ),
                ),
            ],
            options={
                "ordering": ["last_name", "first_name"],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="GroupMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid7,
                        editable=False,
                        help_text="Public UUIDv7 identifier for external references and API routes.",
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("start_date", models.DateField(default=django.utils.timezone.now)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="pwms.group",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last modified this membership record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="membership_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="pwms.role"
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="TransitionLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("object_id", models.PositiveBigIntegerField()),
                ("action", models.CharField(max_length=100)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "from_state",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="pwms.state",
                    ),
                ),
                (
                    "to_state",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="pwms.state",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowGroupAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid7,
                        editable=False,
                        help_text="Public UUIDv7 identifier for external references and API routes.",
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("object_id", models.PositiveBigIntegerField()),
                ("can_view", models.BooleanField(default=True)),
                ("can_edit", models.BooleanField(default=False)),
                ("can_delete", models.BooleanField(default=False)),
                ("can_transition", models.BooleanField(default=False)),
                ("is_primary", models.BooleanField(default=False)),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        help_text="House / Committee (or sub-unit) granted access to the workflow.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_accesses",
                        to="pwms.group",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkflowRolePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid7,
                        editable=False,
                        help_text="Public UUIDv7 identifier for external references and API routes.",
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("can_view", models.BooleanField(default=True)),
                ("can_edit", models.BooleanField(default=False)),
                ("can_delete", models.BooleanField(default=False)),
                ("can_transition", models.BooleanField(default=False)),
                (
                    "allowed_states",
                    models.ManyToManyField(
                        blank=True,
                        help_text="If specified, these permissions only apply in these states",
                        related_name="role_workflow_permissions",
                        to="pwms.state",
                    ),
                ),
                (
                    "group_access",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_permissions",
                        to="pwms.workflowgroupaccess",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_permissions",
                        to="pwms.role",
                    ),
                ),
            ],
            options={
                "ordering": ["role__name"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowStatePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid7,
                        editable=False,
                        help_text="Public UUIDv7 identifier for external references and API routes.",
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("can_view", models.BooleanField(default=True)),
                ("can_edit", models.BooleanField(default=False)),
                ("can_delete", models.BooleanField(default=False)),
                ("can_transition", models.BooleanField(default=False)),
                (
                    "group_access",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="state_permissions",
                        to="pwms.workflowgroupaccess",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_workflow_permissions",
                        to="pwms.state",
                    ),
                ),
            ],
            options={
                "ordering": ["state__name"],
            },
        ),
        migrations.CreateModel(
            name="Transition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid7,
                        editable=False,
                        help_text="Public UUIDv7 identifier for external references and API routes.",
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True,
                        editable=False,
                        help_text="Stable internal identifier for this transition (unique per workflow type).",
                        populate_from="name",
                    ),
                ),
                ("requires_comment", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0)),
                (
                    "allowed_roles",
                    models.ManyToManyField(
                        related_name="allowed_transitions", to="pwms.role"
                    ),
                ),
                (
                    "from_state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transitions_from",
                        to="pwms.state",
                    ),
                ),
                (
                    "notify_roles",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Group members with these roles will receive an email alert when this transition occurs",
                        related_name="notified_transitions",
                        to="pwms.role",
                    ),
                ),
                (
                    "to_state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transitions_to",
                        to="pwms.state",
                    ),
                ),
                (
                    "workflow_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transitions",
                        to="pwms.workflowtype",
                    ),
                ),
            ],
            options={
                "ordering": ["workflow_type", "order", "name"],
            },
        ),
        migrations.AddField(
            model_name="state",
            name="workflow_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="states",
                to="pwms.workflowtype",
            ),
        ),
        migrations.CreateModel(
            name="InternationalResolution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid7,
                        editable=False,
                        help_text="Public UUIDv7 identifier for external references and API routes.",
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True)),
                ("deadline", models.DateTimeField(blank=True, null=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("resolution_number", models.CharField(max_length=50, unique=True)),
                ("adoption_date", models.DateField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_assigned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_owned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "referred_to_groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Groups this workflow is dynamically referred to",
                        related_name="%(class)s_referred",
                        to="pwms.group",
                    ),
                ),
                (
                    "current_state",
                    models.ForeignKey(
                        help_text="Current workflow state. Must belong to ``workflow_type``.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_current",
                        to="pwms.state",
                    ),
                ),
                (
                    "workflow_type",
                    models.ForeignKey(
                        help_text="Reusable state machine (states/transitions) this instance follows.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_instances",
                        to="pwms.workflowtype",
                    ),
                ),
            ],
            options={
                "verbose_name": "International Resolution",
                "verbose_name_plural": "International Resolutions",
            },
        ),
        migrations.AddConstraint(
            model_name="group",
            constraint=models.UniqueConstraint(
                fields=("name", "parent"), name="workflows_group_name_parent_uniq"
            ),
        ),
        migrations.AddIndex(
            model_name="groupmembership",
            index=models.Index(
                fields=["user", "is_active"], name="pwms_groupm_user_id_227c9d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="groupmembership",
            constraint=models.UniqueConstraint(
                fields=("user", "group", "role", "start_date"),
                name="workflows_groupmembership_user_group_role_start_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="transitionlog",
            index=models.Index(
                fields=["content_type", "object_id", "-timestamp"],
                name="pwms_transi_content_2ca88a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workflowgroupaccess",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="pwms_workfl_content_b8fe7b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workflowrolepermission",
            index=models.Index(
                fields=["group_access", "role"], name="pwms_workfl_group_a_df4775_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="workflowrolepermission",
            constraint=models.UniqueConstraint(
                fields=("group_access", "role"),
                name="workflows_workflowrolepermission_access_role_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="workflowstatepermission",
            index=models.Index(
                fields=["group_access", "state"], name="pwms_workfl_group_a_7a209c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="workflowstatepermission",
            constraint=models.UniqueConstraint(
                fields=("group_access", "state"),
                name="workflows_workflowstatepermission_access_state_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="transition",
            constraint=models.UniqueConstraint(
                fields=("workflow_type", "from_state", "to_state"),
                name="workflows_transition_type_from_to_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="transition",
            constraint=models.UniqueConstraint(
                fields=("workflow_type", "slug"),
                name="workflows_transition_type_slug_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="state",
            constraint=models.UniqueConstraint(
                fields=("workflow_type", "name"), name="workflows_state_type_name_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="state",
            constraint=models.UniqueConstraint(
                fields=("workflow_type", "slug"), name="workflows_state_type_slug_uniq"
            ),
        ),
    ]
